new exclusions
Razzeee/script.trakt pull request #378
Opened 2017-04-26 01:42 UTC by Lunatixz

With upcoming Netflix and Amazon plugins there is a user demand to
disable scrobbling when viewing a plugin source... Also there is a need
from script developers to "Pause" trakt scrobbling when needed. After a
user allows script control "script.trakt.paused" property can temp
disable trakt till the media stops or ends then trakt will clear the
property.

2017-04-27 22:25 UTC, razzeee requested changes
Seems like we're missing a file now?

2017-04-27 22:25 UTC, Razzeee commented on resources/language/English/strings.po
> +msgid "Allow script exclusions"
This is worded weird, just go for "Exclude scripts"?

2017-04-27 22:25 UTC, Razzeee commented on resources/language/English/strings.po
> +msgid "Exclude Plugins"
Maybe lowercase "plugins"

2017-04-27 22:25 UTC, Razzeee commented on resources/language/English/strings.po
> +msgctxt "#32185"
I think we're missing the settings.xml changes for this to even work?

2017-04-27 22:36 UTC, Lunatixz commented on resources/language/English/strings.po
> +msgid "Allow script exclusions"
to me "Exclude scripts" sounds like it disables all scripts.... but, whatever works for you.

2017-04-27 23:16 UTC, Razzeee commented on resources/language/English/strings.po
> +msgid "Allow script exclusions"
Then it's fine just seemed weird, as the others are all in the other scheme

2017-04-28 00:44 UTC, Lunatixz commented on resources/language/English/strings.po
> +msgid "Allow script exclusions"
Yeah, aesthetically it doesn't work..

2017-05-01 10:42 UTC, Razzeee commented
Can you add the changes to the settings file again?

2017-05-01 14:05 UTC, Lunatixz commented
Sorry about the missing file, should be fine now.

2017-05-06 10:38 UTC, merged